### ISSUE TITLE
Simulator only showing line

### ISSUE THREAD

**Issue by kevinkhill** [julianschill/klipper-led_effect#208] opened 2024-06-10 00:38 UTC
I got the simulator up and running, but was saddened when the layout did not switch to circle.

I have a 16 pixel ring and want to experiment, but the only layout that works in the simulator for me is `line`. Circle, Triangle and Voron all do not work for me.

**Comment by kevinkhill** [comment] 2024-06-10 01:23
I think I might have found the issue! The difference between the x,y in Rectangle vs all the others, is that they were `int`

I tried adding a method like this
```python
def _push_led_coordinates(self, x, y, size, round_xy=False):
    if round_xy is True:
        self.led_coordinates += [(round(x), round(y), size)]
    else:
        self.led_coordinates += [(x, y, size)]
```
Then switched out `self.led_coordinates += [(x, y, size)]` in `_calc_coordinates()` to use that method.
With rectangle, I didn't use the 4th param to round, but enabling it in Circle worked!
```python
elif self.m_cbLayout.GetValue() == "Circle":
    self.m_spinLines.Enable(False)
    r = distance * self.led_count / (2 * math.pi)
    for i in range(self.led_count):
        a = 2 * math.pi / self.led_count * i
        x = r * math.sin(a)
        y = r * math.cos(a)
        self._push_led_coordinates(x, y, size, round_xy=True)
```
![image](https://github.com/julianschill/klipper-led_effect/assets/266076/bbd5952d-8049-4657-af27-5e0e367cb44b)

(Triangle seems to have a slight issue in the algorithm leaving gaps at certain counts)
![image](https://github.com/julianschill/klipper-led_effect/assets/266076/5608b2ae-8cbc-49e1-8edf-97a283869519)
![image](https://github.com/julianschill/klipper-led_effect/assets/266076/ebef3788-5ce4-4516-8201-d1e8e4ff5aad)

**Comment by julianschill** [comment] 2024-07-11 07:34
I can't reproduce your problem. All shapes are working fine for me. For the triangle: You just can't form a equilateral triangle with any number of leds. That's why there are gaps.
![image](https://github.com/julianschill/klipper-led_effect/assets/13122110/51b7d22e-6b9e-4887-9d14-896a6afc6781)
![image](https://github.com/julianschill/klipper-led_effect/assets/13122110/9668d486-66ee-4ca9-82b7-d94bb9a3acea)
![image](https://github.com/julianschill/klipper-led_effect/assets/13122110/c5b95c44-113b-4033-871e-7e02c84d0e58)

**Comment by julianschill** [comment] 2024-07-11 07:39
Can you maybe elaborate what "not working" means for you? What behaviour are you expecting vs. what 
are you getting?

**Comment by kevinkhill** [comment] 2024-07-11 14:41
When I would try to switch to the other shapes, it would just show nothing up in the top area

**Comment by julianschill** [comment] 2024-07-11 15:02
Are you using the packaged version or are you running it with your own python? If the latter, what python version are you using?

**Comment by julianschill** [comment] 2024-10-13 16:22
Is this still an issue or can I close this?

**Comment by kevinkhill** [comment] 2024-10-13 16:45
Go ahead and close. Thanks for asking 😊

**Closed** 2024-10-13 19:40 UTC
