### ISSUE TITLE
Add code for endstop state and  RPi host and MUC temperature sensors?

### ISSUE THREAD

**Issue by Polar-Ted** [julianschill/klipper-led_effect#58] opened 2022-05-16 19:39 UTC
I would like to have a temp status light for MCU and Pi Host CPU temps.
An endstop state would also  be useful. 

This is the line in printer.cfg that plots the temp in the on-screen graph if that helps. 

[temperature_sensor raspberry_pi]
sensor_type: temperature_host
min_temp: 10
max_temp: 100

[temperature_sensor pico]
sensor_type: temperature_mcu
sensor_mcu: pico
min_temp: 10
max_temp: 100

**Comment by julianschill** [comment] 2022-05-16 19:45
Temperature sensors will be implemented by #35
For Endstops I will have to see what is possible.

**Comment by Polar-Ted** [comment] 2022-05-16 19:56
> Temperature sensors will be implemented by #35 For Endstops I will have to see what is possible.

Maybe I'm writing the effect script incorrectly

When I define  **heater: "temperature_sensor pico"**   the  firmware fails to start with this error

_Internal error during ready callback: Unknown heater 'temperature_sensor pico'
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown_

**Comment by julianschill** [comment] 2022-05-16 19:58
No it is not yet implemented. Your issue is just a duplicate of #35

**Comment by burntcoinpurse** [comment] 2022-07-13 22:15
I got #35 figured out. 👍

**Comment by luisfosoares** [comment] 2022-08-10 15:43
Any progress on this? ETA? I would appreciate it so much thanks

**Comment by julianschill** [comment] 2022-09-21 00:52
No ETA. It is done, when it's done.

**Comment by julianschill** [comment] 2023-02-04 10:29
Endstops can now trigger the new homing effect.

**Closed by julianschill** 2023-02-04 10:29 UTC
Labels: enhancement, new effect, fixed_in_next_version
